name: "Dev Check"

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/mcp_check_base.yaml
    with:
      environment: "dev"
      aws-region: "ap-southeast-2"
