name: "QAS Deployment"

on:
  push:
    branches:
      - qas
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/mcp_deploy_base.yaml
    with:
      environment: "qas"
      aws-region: "ap-southeast-2"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MANAGEMENT_API_KEY: ${{ secrets.MANAGEMENT_API_KEY }}
